### ISSUE TITLE
请问怎么更新这个工具？

### ISSUE THREAD

**Issue by monobo1989** [UIforFreedom/UIF#11]
不想重新设置和添加订阅。

**Comment by UIforFreedom** [comment]
在设置里面启用 `自动更新UIF` 就行了。UIF 会自动检查新版本，然后会自动下载安装，包括 Sing-Box 内核。一切都是自动的，不需要你特别关注。  然而如果你说，你想要把 UIF 的配置转移到其他机器，理论上将 `uif.json` 这个文件粘贴到目录里面就行了（估计有 Bug，有空我再搞一搞）。
