### ISSUE TITLE
请问为什么使用sing-box不再支持的geosite和geoip数据库

### ISSUE THREAD

**Issue by PR2403** [UIforFreedom/UIF#14]
我看到已经使用了rule_set，为什么还保留弃用的db数据库?
geoip字段也已经被弃用了

还有dns rules中
```
"rule_set": [
          "geoip-cn"
        ],
```
我没有看明白为什么在dns时使用ip规则，singbox劫持了所有dns请求，客户端上填的dns服务器地址不会影响，为什么要匹配dns服务器地址？

基本能做到开箱即用，web界面，我真的很喜欢，但自定义太少了。我现在用的是gui.for.singbox，放到旁路由上，需要的时候开vnc进桌面环境改参数，但还是有点太占内存了，好处就是自定义参数很多，很省事。如果UIF可以做到详细的自定义或者直接开放json修改，我会立刻搬过来。

下面是功能请求
能否允许对路由和dns规则进行更详细的设置，开放规则集，或者可以允许修改最终的json方便高级用户diy

**Comment by UIforFreedom** [comment]
> 我看到已经使用了rule_set，为什么还保留弃用的db数据库?

为了可以在路由中添加自己喜欢的分流，一个个去添加 rule_set 的 url 太麻烦了。虽然 geo 已被抛弃了，实际上 rule_set 还是用 geo 的东西，本质内容是没有变的只是换了个格式而已

> 如果UIF可以做到详细的自定义或者直接开放json修改，我会立刻搬过来。

建议直接使用内核即可，定制程度高，意味着封装更少。本来就是矛盾的东西，不能既要又要

> 我没有看明白为什么在dns时使用ip规则

这也是 sing-box 先进的地方，在设置中我已经说得很明白了

> 能否允许对路由和dns规则进行更详细的设置，开放规则集

路由规则完全可以自定制，支持的规则字段是全网最全的。DNS 规则后续可以跟随路由规则。geo 等 sing-box 删了这个功能再说。

> 或者可以允许修改最终的json方便高级用户diy

不会让用户自定义 JSON ，那还不如直接去用内核。说句不好听的（没有恶意），你连为什么要用 IP 分流都搞不清楚，可能最后自己去自定义配置内容都不一定有我配的好。在 Sing-Box 你提这些要求随时都会被判定为 end user，我算是非常友好的了... 

最后感谢你的支持。

**Comment by PR2403** [comment]
重新看了下文档，发现是匹配返回的ip，不符合就丢弃结果。思维定势以为和域名一样是。是我到问题
主要是有时候不方便用ssh，要是网页端有个json编辑器，编辑完一按重启就能重启核心，再有个日志,也挺好。要是会做网页就好了<_<
