### ISSUE TITLE
入站配置开启前主页可用检测均正常, 开启后均-1

### ISSUE THREAD

**Issue by ryuryu08** [UIforFreedom/UIF#15]

**Comment by ryuryu08** [comment]
关闭入站配置中的“设置系统代理”后则恢复正常.

**Comment by ryuryu08** [comment]
看起来像是系统代理设置的参数和控制面板中的不一致
`Get "https://www.github.com": proxyconnect tcp: dial tcp 127.0.0.1:45141: connect: connection refused`

**Comment by UIforFreedom** [comment]
估计是自动设置代理失败了。具体要看日志
