### ISSUE TITLE
链式代理如何使用？

### ISSUE THREAD

**Issue by github19999** [UIforFreedom/UIF#16]
我想将流量先转发到代理 A，再转发到代理 B

**Comment by UIforFreedom** [comment]
出站节点 `操作` -> `配置` -> `拨号设置` -> `detour` 

小心设置，否则回环自己负责

**Comment by github19999** [comment]
A、B节点同时打开，我想B节点作为落地节点，在A中选择：操作 -> 配置 -> 拨号设置 -> detour（选择B节点），然后保存，但无法实现B落地。不知道用法对不对。

**Comment by github19999** [comment]
接上，用法应该没问题，如果A、B都是通的，可以实现落地。问题是，如果B是一个被封的vps，当在A中选择：操作 -> 配置 -> 拨号设置 -> 链式代理（选择B节点），是无法实现B落地的，一直不通。这样的前置代理感觉没有意义，是否能进行优化。

**Comment by UIforFreedom** [comment]
你搞反了，B 是被封的，你应该在B的设置中选中A，而不是在B中选中A

**Comment by UIforFreedom** [comment]
在主页切换到 `简化版`。选中B即可。或者你可以在路由中设置让全部流量都走B节点

**Comment by github19999** [comment]
OK
