### ISSUE TITLE
请教一下这个项目的逻辑是怎样的？

### ISSUE THREAD

**Issue by sky22333** [UIforFreedom/UIF#17]
如题，看了下文档，感觉有点模糊。

**请教一下这个项目的逻辑：这个面板是既可以充当客户端，也可以充当服务端吗？**

**例如我`本地服务器`充当`客户端`部署面板，然后`B服务器`充当`服务端(后端)`部署面板，`本地服务器`填入`B服务器的API`**

**然后在`本地服务器`面板增加的节点配置，`B服务器`会自动创建这个服务端节点配置吗？然后自动连接上这个节点？**

是这个逻辑吗？如果不是的话希望大佬能解惑一下，感谢

>另外我觉得可以照着这个逻辑尝试实现一下，可以进一步简化操作

**Comment by UIforFreedom** [comment]
> 请教一下这个项目的逻辑：这个面板是既可以充当客户端，也可以充当服务端吗？

是的。你可以尝试一下简化版（主页点击一下切换），跟常见的桌面客户端是一样的

> 例如我本地服务器充当客户端部署面板，然后B服务器充当服务端(后端)部署面板，本地服务器填入B服务器的API

你想得太复杂了。直接用 SSH 客户端做类比，Web 其实也就是个界面，你想连接上哪部电脑直接填密码和 IP 就行了
