### ISSUE TITLE
订阅拉取不了节点，一直提示错误，大佬看看。。。

### ISSUE THREAD

**Issue by drw2005** [UIforFreedom/UIF#18]
用自己常用的机场订阅也是这类提示，用github上的订阅也是下面这种提示：
Get "https://testingcf.jsdelivr.net/gh/chengaopan/AutoMergePublicNodes@master/list.yml": proxyconnect tcp: dial tcp 127.0.0.1:63272: connectex: No connection could be made because the target machine actively refused it. Get "https://testingcf.jsdelivr.net/gh/chengaopan/AutoMergePublicNodes@master/list.yml": proxyconnect tcp: dial tcp 127.0.0.1:63272: connectex: No connection could be made because the target machine actively refused it.

用Clash.Verge倒是能正常拉取。

**Comment by JimmyHuang454** [comment]
我可以拉啊。我测试的是这个：https://testingcf.jsdelivr.net/gh/chengaopan/AutoMergePublicNodes@master/list.yml

主页的log显示什么？

**Comment by JimmyHuang454** [comment]
我可以拉啊。测试的是这个 https://testingcf.jsdelivr.net/gh/chengaopan/AutoMergePublicNodes@master/list.yml

**Comment by drw2005** [comment]
> 我可以拉啊。测试的是这个 https://testingcf.jsdelivr.net/gh/chengaopan/AutoMergePublicNodes@master/list.yml

你这个也拉取不了，还是这种错误。
真神奇。

**Comment by drw2005** [comment]
> 我可以拉啊。测试的是这个 https://testingcf.jsdelivr.net/gh/chengaopan/AutoMergePublicNodes@master/list.yml

应该是我的问题，我再检查一下。

**Comment by UIforFreedom** [comment]
最新版已优化这个问题。UIF 会先用直连拉一次订阅，发现不行后再用代理拉一次，问题出现在第二次上，属于比较隐蔽的Bug

**Comment by drw2005** [comment]
> 最新版已优化这个问题。UIF 会先用直连拉一次订阅，发现不行后再用代理拉一次，问题出现在第二次上，属于比较隐蔽的Bug

用最新版试了下，还是不行，平时自己用的机场，用Clash.Verge正常拉取。

**Comment by UIforFreedom** [comment]
你是啥系统？

**Comment by drw2005** [comment]
> 你是啥系统？

64位win7

**Comment by UIforFreedom** [comment]
> > 你是啥系统？
> 
> 64位win7，在另一台win11下能正常拉取。 支持一下win7吧。

内核不支持 win7

**Comment by drw2005** [comment]
> > > 你是啥系统？
> > 
> > 
> > 64位win7，在另一台win11下能正常拉取。 支持一下win7吧。
> 
> 内核不支持 win7

明白了，谢谢，软件很好用，准备安装到软路由上试试。
