### ISSUE TITLE
docker部署，入站开启HTTP/Socks失败，并且端口没有被占用

### ISSUE THREAD

**Issue by xiaoyutx94** [UIforFreedom/UIF#19]
![image](https://github.com/user-attachments/assets/91dbfed8-e12e-492e-bb38-a862cc0d1921)

![image](https://github.com/user-attachments/assets/0be5fd55-4600-44d8-aaa1-a98e7966b482)

并且9191端口也没有启动成功。

**Comment by UIforFreedom** [comment]
docker里面开启http入站需要关闭自动设置系统代理
