### ISSUE TITLE
vless支持问题

### ISSUE THREAD

**Issue by LLIce** [UIforFreedom/UIF#21]
自添加节点时，ui界面没有reality选项，json界面public_key属性会自动重置为jNXHt1yRo0vDu 开头的一串字符

**Comment by UIforFreedom** [comment]
订阅是支持的，但是自添加没有 reality 和 shadowtls 的选项

**Comment by LLIce** [comment]
reality: {
        enabled: false,
        handshake: {
          server: "google.com",
          server_port: 443,
        },
        private_key: "UuMBgl7MXTPx9inmQp2UC7Jcnwc6XYbwDNebonM-FCc",
        public_key: "jNXHt1yRo0vDuchQlIP6Z0ZvjT3KtzVI-T4E7RoLJS0",

我试了下丢了个vless订阅进去，public_key这个值也会自动重置为jNXHt1yRo0vDuchQlIP6Z0ZvjT3KtzVI-T4E7RoLJS0

**Comment by UIforFreedom** [comment]
试试最新版的，应该已修复。订阅支持添加 reality 节点，但不支持自定义修改或添加。
