### ISSUE TITLE
关于自动优选的一些疑问

### ISSUE THREAD

**Issue by orangestar0829** [UIforFreedom/UIF#23]
版本 面板  0.3.21 /后端  1.10.0-beta.8
环境 Docker

问题1：
![image](https://github.com/user-attachments/assets/0b24dfad-af79-40ae-8baa-6a37632a1938)
官方教程中自动优选有个最低延迟的设置，但是在目前版本中没了，替代的是排序误差
![image](https://github.com/user-attachments/assets/8f7b24e5-5ddc-45c6-9586-9aa00d3d5708)
这俩含义是否一致呢？

问题2：
我在面板界面修改了 排序误差，也提示配置保存成功，内核已更新。但是一旦刷新页面就恢复默认值70

**Comment by UIforFreedom** [comment]
> 官方教程中自动优选有个最低延迟的设置，但是在目前版本中没了，替代的是排序误差

已更新文档。

> 我在面板界面修改了 排序误差，也提示配置保存成功，内核已更新。但是一旦刷新页面就恢复默认值70

Bug。但不影响实际使用，只是没保存好。最新版已修复
