### ISSUE TITLE
docker版，只要启动入站的socks 端口，运行就变成了未运行。

### ISSUE THREAD

**Issue by haha110110** [UIforFreedom/UIF#28]
版本用的最新的DOCKER版，只要已启动SOCKS入站，后端内核就停止了。

0000 2024-10-12 06:42:08 INFO ntp: updated time: 2024-10-12 06:42:08 +0000

+0000 2024-10-12 06:42:08 INFO clash-api: restful api listening at [::]:9191

+0000 2024-10-12 06:42:08 INFO inbound/mixed[HTTP/Socks0]: tcp server started at 0.0.0.0:9110

FATAL[0000] start service: initialize inbound/mixed[HTTP/Socks0]: initialize system proxy: unsupported desktop environment

core err: exit status 1
failed to get uif newestVersion.
failed to get core newestVersion.
{"status":1,"res":"no new version"}
set auto restart core after: 24

**Comment by UIforFreedom** [comment]
把http自动配置系统代理关掉

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 10 月 12 日星期六 14:49, haha110110 ***@***.***(mailto:2024 年 10 月 12 日星期六 14:49, haha110110 <<a href=)> 来信：

**Comment by haha110110** [comment]
太感谢了。问题解决！如果有时间，能否帮我解答一下为什么开着系统代理就不行么？其实我也希望这台服务器可以直接访问，方便pull image。

**Comment by UIforFreedom** [comment]
还要解答什么？ 手动去修改 http 代理就行了啊

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 10 月 12 日星期六 15:00, haha110110 ***@***.***(mailto:2024 年 10 月 12 日星期六 15:00, haha110110 <<a href=)> 来信：
