### ISSUE TITLE
Ubnutu20.04无法使用

### ISSUE THREAD

**Issue by it-glen** [UIforFreedom/UIF#3]
![image](https://github.com/UIforFreedom/UIF/assets/73119626/2c7af096-2a13-44ad-8e31-f0fd1636448b)
![image](https://github.com/UIforFreedom/UIF/assets/73119626/c8986374-d203-4bcc-92df-3700165b6e3f)
![image](https://github.com/UIforFreedom/UIF/assets/73119626/e468acbd-9bba-476f-9271-17e65f1828eb)
如图，Ubnutu20.04的 GLIBC 版本太低，升级太危险。

**Comment by UIforFreedom** [comment]
看起来应该是依赖了CGO（编译时可以去掉），你可以先试试本地运行sing box 内核，看看是否也需要该依赖

**Comment by it-glen** [comment]
> 看起来应该是依赖了CGO（编译时可以去掉），你可以先试试本地运行sing box 内核，看看是否也需要该依赖

sing-box内核怎么运行啊，直接这样
![image](https://github.com/UIforFreedom/UIF/assets/73119626/0130ef74-a53d-43d2-8c77-ae4c4bf3353c)

**Comment by UIforFreedom** [comment]
请尝试最新版
