### ISSUE TITLE
docker 版，socks节点如何配置username 和 passowrd?

### ISSUE THREAD

**Issue by haha110110** [UIforFreedom/UIF#30]
版本目前用的是latest。
订阅过来的链接，socks节点无username 和password信息。
奇怪的是我其中一个服务器uif订阅的节点只有一个socks获取到username和password信息。而另外一个地方的服务器获取不到username和password信息。

![ksnip_20241012-225342](https://github.com/user-attachments/assets/dbf45697-49d1-4fb2-b128-8705bf9bb557)

**Comment by UIforFreedom** [comment]
订阅不支持 socks；也不怎么想支持 socks 等无加密的代理协议。 只能手动添加 socks。

**Comment by haha110110** [comment]
补充 cat uif.json文件 发现订阅的链接的信息里有username 和password 信息。但是给socks节点配置proxy chain后，core_的那个json文件里不包括账号和密码的信息。

**Comment by UIforFreedom** [comment]
无法复现
