### ISSUE TITLE
专业版-出站-订阅测速问题

### ISSUE THREAD

**Issue by orangestar0829** [UIforFreedom/UIF#31]
版本 面板 0.3.22 /后端 1.10.0-beta.11 （刚拉的最新镜像）
环境 Docker

问题1：
专业版-出站-订阅测速 使用的是 设置里 自动优选设置的测速地址吗？

问题2：
同一订阅在专业版测速均为-1，简化版出站测速有延迟。并且不管专业版，简化版都能正常访问网络
![专业版测速情况](https://github.com/user-attachments/assets/880327c9-bb76-4f83-aeef-49e7c0c4384f)
![简化版测速情况](https://github.com/user-attachments/assets/986fe406-92d0-41ad-b681-3dc1b0b449e5)

**Comment by UIforFreedom** [comment]
你确定不是你订阅节点有太多不可用？ 按理来说，简化版和专业版的延迟都会显示的。但你没有提供复现方法，我不知道哪里有问题，也不知道如何修复。 你可以私聊我的tg发订阅过来

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 10 月 14 日星期一 00:15, orangestar0829 ***@***.***(mailto:2024 年 10 月 14 日星期一 00:15, orangestar0829 <<a href=)> 来信：

**Comment by orangestar0829** [comment]
不是，你看图里的日本俩节点，日本01-hy2，日本02-hy2.在专业版就显示-1，简化版就有显示。
我这边怎么试专业版都是-1，百分百复现这个。测速的时候也没看到日志报错
我找下tg，发送给你试试看。

**Comment by UIforFreedom** [comment]
试试最新版的。是订阅转换出了问题，导致你必须要不启用某个节点才能使用。

**Comment by orangestar0829** [comment]
更新到最新版，并且删除所有订阅，重新添加订阅后测试
![image](https://github.com/user-attachments/assets/e9f261af-d82b-478b-908d-bef5173a2dba)
单个节点延迟测试还是-1，全部节点测试也是-1

**Comment by UIforFreedom** [comment]
下最新版的，我已编译好了
