### ISSUE TITLE
Ubuntu无法设置系统代理，不能正常使用

### ISSUE THREAD

**Issue by parmesanC** [UIforFreedom/UIF#32]
> Working at: /usr/bin/uif
> Password: a708730f-5f08-4307-9dbb-8779e96890a6
> open port:26497
> cached UIFAPI port: 39323
> cached UIFAPIDirect port: 35371
> Web Address: 0.0.0.0:3533
> API Address: 0.0.0.0:26497
> <<<< UIF running >>>>
> Setting not to open web.
> +0800 2024-10-15 20:30:28 INFO router: updated default interface wlp1s0, index 2
> 
> +0800 2024-10-15 20:30:28 INFO inbound/mixed[HTTP/Socks0]: tcp server started at 127.0.0.1:9110
> 
> FATAL[0000] start service: initialize inbound/mixed[HTTP/Socks0]: set system proxy: set system proxy: unable to set as root
> 
> core err: exit status 1
> failed to get uif newestVersion.
> failed to get core newestVersion.
> {"status":1,"res":"no new version"}
> Get "https://www.baidu.com": proxyconnect tcp: dial tcp 127.0.0.1:39323: connect: connection refused
> 
> Get "https://www.baidu.com": proxyconnect tcp: dial tcp 127.0.0.1:35371: connect: connection refused
> Get "https://www.github.com": proxyconnect tcp: dial tcp 127.0.0.1:39323: connect: connection refused
> Get "https://www.netflix.com": proxyconnect tcp: dial tcp 127.0.0.1:39323: connect: connection refused
> 
> Get "https://www.github.com": proxyconnect tcp: dial tcp 127.0.0.1:35371: connect: connection refused
> Get "https://www.instagram.com": proxyconnect tcp: dial tcp 127.0.0.1:39323: connect: connection refused
> 
> Get "https://www.netflix.com": proxyconnect tcp: dial tcp 127.0.0.1:35371: connect: connection refused
> Get "https://www.youtube.com": proxyconnect tcp: dial tcp 127.0.0.1:39323: connect: connection refused
> 
> Get "https://www.google.com": proxyconnect tcp: dial tcp 127.0.0.1:39323: connect: connection refused
> Get "https://www.youtube.com": proxyconnect tcp: dial tcp 127.0.0.1:35371: connect: connection refused
> 
> Get "https://www.instagram.com": proxyconnect tcp: dial tcp 127.0.0.1:35371: connect: connection refused
> Get "https://www.google.com": proxyconnect tcp: dial tcp 127.0.0.1:35371: connect: connection refused
![image](https://github.com/user-attachments/assets/0cace2b6-ac09-4944-acf9-b76ffaf65ced)
无法使用127.0.0.1:26497链接后端会报错无法连接后端，UIF 功能不可用，请确保本机正确地安装 UIF 并启动！只能使用http://192.168.**.***:26497

**Comment by UIforFreedom** [comment]
错误就是字面意思：
> set system proxy: set system proxy: unable to set as root

如无法自动设置 http 代理，请在 http `配置` 中取消自动设置系统代理
