### ISSUE TITLE
按入站规则路由问题

### ISSUE THREAD

**Issue by nidzz1** [UIforFreedom/UIF#33]
你好，我现在是添加了两个入站规则9110端口和9111端口，其它都入站规则都相同，然后导入了订阅，路由按照了入站规则进行匹配，我发现没效果，无论我走哪个代理端口，都只是固定走一个出口。
我的需求是9110入站的请求，走订阅的A节点，9111的入站请求走B节点，这个现阶段没这个功能吗？

**Comment by UIforFreedom** [comment]
有这个功能！ 添加一条路由规则即可

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 10 月 16 日星期三 08:36, pubz ***@***.***(mailto:2024 年 10 月 16 日星期三 08:36, pubz <<a href=)> 来信：

**Comment by nidzz1** [comment]
牛逼大哥
