### ISSUE TITLE
非常简单好用的工具,不过有个问题,docker下如何升级或导出目前的配置文件

### ISSUE THREAD

**Issue by sh2288** [UIforFreedom/UIF#34]
非常简单好用的工具,不过有个问题,docker下如何升级新版本或导出目前的配置文件
毕竟这是个长期使用的工具,希望能有个版本升级的功能或指导
感谢大佬的辛苦付出,望回复~

**Comment by UIforFreedom** [comment]
去到设置启用自动更新即可。 你仅需保存节点订阅即可，并不需要特别保存uif的配置（直接用默认的）

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 10 月 16 日星期三 13:55, sh2288 ***@***.***(mailto:2024 年 10 月 16 日星期三 13:55, sh2288 <<a href=)> 来信：
