### ISSUE TITLE
http/socks入站能否支持ipv6

### ISSUE THREAD

**Issue by bupt2017** [UIforFreedom/UIF#38]
我手动修改配置文件，重启核心之后，配置文件又会恢复成prefer_ipv4

**Comment by UIforFreedom** [comment]
目前不支持 ipv6 。 等需用的人多了，需求高了再加

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 10 月 26 日星期六 12:21, bupt2017 ***@***.***(mailto:2024 年 10 月 26 日星期六 12:21, bupt2017 <<a href=)> 来信：

**Comment by bupt2017** [comment]
出门在外想要连接设备只能通过公网。但是国内有公网ipv4的毕竟是少数，但是拥有公网ipv6的人却很多，手机流量也都有ipv6。建议可以加上一个切换选项。或者默认配置去掉prefer_ipv4。

**Comment by UIforFreedom** [comment]
试试最新版，已加上
