### ISSUE TITLE
更新订阅可否加一个可选代理？

### ISSUE THREAD

**Issue by kknd222** [UIforFreedom/UIF#39]
现在尴尬的是有些订阅链接已经被拦了，没法连通

**Comment by UIforFreedom** [comment]
更新订阅时，uif 会同时尝试 通过代理 和 不通过代理 两种方式获取最新订阅内容。所以无须用户特别去关心有没有通过代理获取内容

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 11 月 2 日星期六 09:32, kknd222 ***@***.***(mailto:2024 年 11 月 2 日星期六 09:32, kknd222 <<a href=)> 来信：
