### ISSUE TITLE
[Feature] 增加快捷键控制内核开关和面板开关

### ISSUE THREAD

**Issue by achieve-dream1221** [UIforFreedom/UIF#40]
可以增加快捷键, 快捷打开或关闭内核以及面板吗

**Comment by UIforFreedom** [comment]
不考虑

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 11 月 6 日星期三 09:55, achieve_dream ***@***.***(mailto:2024 年 11 月 6 日星期三 09:55, achieve_dream <<a href=)> 来信：
