### ISSUE TITLE
订阅链接加个定时更新功能呗

### ISSUE THREAD

**Issue by star8618** [UIforFreedom/UIF#41]
订阅链接加个定时更新功能呗，现在的机场太不稳定了，或者外网掉了，自动更新订阅链接以及故障转移。好像不支持dns转发功能。

**Comment by UIforFreedom** [comment]
不考虑添加定时更新订阅，因为订阅就不应该经常变换。自动负载均衡是机场去做的事情，如果这么简单的东西都做不好，建议换个机场。
