### ISSUE TITLE
能否增加支持ARM架构的银河麒麟？

### ISSUE THREAD

**Issue by relaxxu** [UIforFreedom/UIF#42]
如果能向V2rayA一样支持银河麒麟V10就好了，好像是因为银河麒麟的内核版本太低，后端显示安装成功但前端无法显示。

**Comment by UIforFreedom** [comment]
取决于 sing box 支不支持

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 11 月 7 日星期四 15:13, relaxxu ***@***.***(mailto:2024 年 11 月 7 日星期四 15:13, relaxxu <<a href=)> 来信：

**Comment by relaxxu** [comment]
怎样才能支持singbox呢？

**Comment by UIforFreedom** [comment]
sing box 支持的话，uif 也会支持，没人具体去测测sing box是否支持，比如说 tun 能不能用， 这种系统用的人太少，适配只会浪费开发者时间

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 11 月 7 日星期四 15:52, relaxxu ***@***.***(mailto:2024 年 11 月 7 日星期四 15:52, relaxxu <<a href=)> 来信：

**Comment by relaxxu** [comment]
好的，谢谢！
