### ISSUE TITLE
docker部署，测速全部为-1

### ISSUE THREAD

**Issue by lm970585581** [UIforFreedom/UIF#45]
同样的问题，按照文档使用docker部署到Ubuntu服务器里，无法测试网速，无法成功代理，不知道怎么使用
![image](https://github.com/user-attachments/assets/48d0ca9c-59d4-42b8-afc5-a1085b1500d0)

查看日志时发现报错：
2024/11/22 09:52:06 http: panic serving 192.168.131.67:50865: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
net/http.(*conn).serve.func1()
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:1873 +0xb9
panic({0x953800?, 0xe2de50?})
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/runtime/panic.go:920 +0x270
bytes.(*Buffer).Len(...)
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/bytes/buffer.go:79
net/http.NewRequestWithContext({0xac4d90?, 0xe6fac0}, {0xc00034603a?, 0x0?}, {0xc00045e120?, 0x22?}, {0xac0280, 0x0?})
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/request.go:901 +0x3b1
net/http.NewRequest(...)
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/request.go:839
github.com/uif/uifd/uif.HTTPWithPort({0xc00045e120, 0x22}, {0x0?, 0x0}, {0xc00034604a, 0x0}, {0xc00034603a, 0x3}, {0xc00001206e, 0x2})
        D:/a/UIF/UIF/uifd/uif/http_get.go:69 +0x2d5
main.Service({0xac3e00?, 0xc000340000}, 0xc000214000)
        D:/a/UIF/UIF/uifd/service/service.go:175 +0x8a5
net/http.HandlerFunc.ServeHTTP(0x10?, {0xac3e00?, 0xc000340000?}, 0xc00044c06c?)
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:2141 +0x29
net/http.(*ServeMux).ServeHTTP(0x4107e5?, {0xac3e00, 0xc000340000}, 0xc000214000)
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:2519 +0x142
net/http.serverHandler.ServeHTTP({0xac2518?}, {0xac3e00?, 0xc000340000?}, 0x6?)
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:2943 +0x8e
net/http.(*conn).serve(0xc00043c510, {0xac4e70, 0xc0000fe180})
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:2014 +0x5f4
created by net/http.(*Server).Serve in goroutine 19
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:3091 +0x5cb
2024/11/22 09:52:06 http: panic serving 192.168.131.67:50866: runtime error: invalid memory address or nil pointer dereference
goroutine 23 [running]:
net/http.(*conn).serve.func1()
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:1873 +0xb9
panic({0x953800?, 0xe2de50?})
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/runtime/panic.go:920 +0x270
bytes.(*Buffer).Len(...)
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/bytes/buffer.go:79
net/http.NewRequestWithContext({0xac4d90?, 0xe6fac0}, {0xc0001421b6?, 0x0?}, {0xc000280300?, 0x1e?}, {0xac0280, 0x0?})
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/request.go:901 +0x3b1
net/http.NewRequest(...)
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/request.go:839
github.com/uif/uifd/uif.HTTPWithPort({0xc000280300, 0x1e}, {0x0?, 0x0}, {0xc0001421c6, 0x0}, {0xc0001421b6, 0x3}, {0xc000012118, 0x2})
        D:/a/UIF/UIF/uifd/uif/http_get.go:69 +0x2d5
main.Service({0xac3e00?, 0xc0003400e0}, 0xc000214200)
        D:/a/UIF/UIF/uifd/service/service.go:175 +0x8a5
net/http.HandlerFunc.ServeHTTP(0x10?, {0xac3e00?, 0xc0003400e0?}, 0xc00044c1ec?)
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:2141 +0x29
net/http.(*ServeMux).ServeHTTP(0x4107e5?, {0xac3e00, 0xc0003400e0}, 0xc000214200)
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:2519 +0x142
net/http.serverHandler.ServeHTTP({0xac2518?}, {0xac3e00?, 0xc0003400e0?}, 0x6?)
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:2943 +0x8e
net/http.(*conn).serve(0xc00025e240, {0xac4e70, 0xc0000fe180})
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:2014 +0x5f4
created by net/http.(*Server).Serve in goroutine 19
        C:/hostedtoolcache/windows/go/1.21.13/x64/src/net/http/server.go:3091 +0x5cb
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6de011]

**Comment by lm970585581** [comment]
这是主页面，后端是连着的
![image](https://github.com/user-attachments/assets/5cf8cb72-9a12-4fe4-b89f-7a9d8a14a18a)

**Comment by lm970585581** [comment]
后端日志里测速正常：
![image](https://github.com/user-attachments/assets/65412231-81af-4677-ad1c-e58830f8b75d)

**Comment by UIforFreedom** [comment]
试试最新版的，昨天的一个bug，最新版已经修复了，docker 的缓存没刷新过来

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 11 月 22 日星期五 18:02, H.U.C-王子 ***@***.***(mailto:2024 年 11 月 22 日星期五 18:02, H.U.C-王子 <<a href=)> 来信：
