### ISSUE TITLE
软件经常自动退出.

### ISSUE THREAD

**Issue by w796933** [UIforFreedom/UIF#46]
root@LS-555827-45627:/usr/bin/uif# systemctl status ui4freedom
○ ui4freedom.service - uif service
     Loaded: loaded (/etc/systemd/system/ui4freedom.service; enabled; preset: enabled)
     Active: inactive (dead) since Sat 2024-11-23 12:16:52 HKT; 8s ago
   Duration: 10.019s
    Process: 517 ExecStart=/usr/bin/uif/uif (code=exited, status=0/SUCCESS)
   Main PID: 517 (code=exited, status=0/SUCCESS)
        CPU: 52ms

Nov 23 12:16:52 LS-555827-45627 uif[522]: github.com/uif/uifd/uif.CheckUpdate()
Nov 23 12:16:52 LS-555827-45627 uif[522]:         D:/a/UIF/UIF/uifd/uif/uif.go:788 +0xf
Nov 23 12:16:52 LS-555827-45627 uif[522]: github.com/uif/uifd/uif.Update()
Nov 23 12:16:52 LS-555827-45627 uif[522]:         D:/a/UIF/UIF/uifd/uif/uif.go:910 +0x2f
Nov 23 12:16:52 LS-555827-45627 uif[522]: main.StartupCore()
Nov 23 12:16:52 LS-555827-45627 uif[522]:         D:/a/UIF/UIF/uifd/service/service.go:285 +0x8a
Nov 23 12:16:52 LS-555827-45627 uif[522]: created by main.Entry in goroutine 1
Nov 23 12:16:52 LS-555827-45627 uif[522]:         D:/a/UIF/UIF/uifd/service/service.go:359 +0x71
Nov 23 12:16:52 LS-555827-45627 uif[517]: Process exited with error: exit status 2
Nov 23 12:16:52 LS-555827-45627 systemd[1]: ui4freedom.service: Deactivated successfully.

**Comment by UIforFreedom** [comment]
已知bug，最新版已修复。重新运行一键脚本安装最新版

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 11 月 23 日星期六 12:19, w796933 ***@***.***(mailto:2024 年 11 月 23 日星期六 12:19, w796933 <<a href=)> 来信：

**Comment by w796933** [comment]
我早上用一键脚本安装的. 你是刚刚更新的吗?

**Comment by w796933** [comment]
新版本可用检测. 安装了好几台机器.  可用检测 里面的网站全部打×的. 之前的版本全部正常的.

**Comment by UIforFreedom** [comment]
在试试最新版的 v24.11.23。cdn 的缓存老是刷新不过来

**Comment by w796933** [comment]
[root@localhost ~]# systemctl status ui4freedom
● ui4freedom.service - uif service
   Loaded: loaded (/etc/systemd/system/ui4freedom.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

Nov 23 22:25:22 localhost.localdomain uif[32358]: D:/a/UIF/UIF/uifd/uif/uif.go:827 +0x17
Nov 23 22:25:22 localhost.localdomain uif[32358]: github.com/uif/uifd/uif.CheckUpdate()
Nov 23 22:25:22 localhost.localdomain uif[32358]: D:/a/UIF/UIF/uifd/uif/uif.go:788 +0xf
Nov 23 22:25:22 localhost.localdomain uif[32358]: github.com/uif/uifd/uif.Update()
Nov 23 22:25:22 localhost.localdomain uif[32358]: D:/a/UIF/UIF/uifd/uif/uif.go:910 +0x2f
Nov 23 22:25:22 localhost.localdomain uif[32358]: main.StartupCore()
Nov 23 22:25:22 localhost.localdomain uif[32358]: D:/a/UIF/UIF/uifd/service/service.go:285 +0x8a
Nov 23 22:25:22 localhost.localdomain uif[32358]: created by main.Entry in goroutine 1
Nov 23 22:25:22 localhost.localdomain uif[32358]: D:/a/UIF/UIF/uifd/service/service.go:359 +0x71
Nov 23 22:25:22 localhost.localdomain uif[32358]: Process exited with error: exit status 2
还是一样 自动退出.

**Comment by UIforFreedom** [comment]
看看你 UIF 的版本，可以用以下方法：

- 直接在面板首页可以看到

- 打开文件 /usr/bin/uif/version/uif.txt 即可看到

最新版本是：v24.11.24， 我用这个版本测试是没问题的。

**Comment by w796933** [comment]
服务器多个IP的情况下.  全局 tun 不生效.

[root@localhost ~]# ip r
default via 103.58.5.129 dev enp3s0 proto static metric 100 
103.58.5.128/26 dev enp3s0 proto kernel scope link src 103.58.5.176 metric 100 
103.58.5.128/26 dev enp3s0 proto kernel scope link src 103.58.5.177 metric 100 
103.58.5.128/26 dev enp3s0 proto kernel scope link src 103.58.5.178 metric 100 
172.19.0.0/30 dev tun0 proto kernel scope link src 172.19.0.1 

curl ip.sb  还是显示服务器IP.

**Comment by UIforFreedom** [comment]
> 服务器多个IP的情况下. 全局 tun 不生效.
> 
> [root@localhost ~]# ip r default via 103.58.5.129 dev enp3s0 proto static metric 100 103.58.5.128/26 dev enp3s0 proto kernel scope link src 103.58.5.176 metric 100 103.58.5.128/26 dev enp3s0 proto kernel scope link src 103.58.5.177 metric 100 103.58.5.128/26 dev enp3s0 proto kernel scope link src 103.58.5.178 metric 100 172.19.0.0/30 dev tun0 proto kernel scope link src 172.19.0.1
> 
> curl ip.sb 还是显示服务器IP.

自动配置路由无法做到适配所有情况，你可以把自动配置路由关了，然后自己去配路由让所有流量都走 tun，具体怎么配置，我没有义务告诉你。

**Comment by w796933** [comment]
你肯定没有义务. 但是也不需要这样的口气.如果开源太难.随时可以捐赠.

**Comment by w796933** [comment]
有偿请教.
