### ISSUE TITLE
bt流量绕过代理问题

### ISSUE THREAD

**Issue by shakugannokanade** [UIforFreedom/UIF#47]
![image](https://github.com/user-attachments/assets/02f19ad5-9745-44d0-ae96-076507cc3f19)
![image](https://github.com/user-attachments/assets/ada2399f-8994-4b15-b615-2ee873fb859d)
![6ceb04e82da73dcc44e03aa5fce19316](https://github.com/user-attachments/assets/be676b4c-eb22-4e5a-8b9a-fa1ee3da57af)
入站为TUN模式，分流策略为国内直连国外代理。在路由设置中添加了bittorrent协议直连的规则，bt软件中也显示连接为BT类型，但查看代理连接时发现应用final规则走了代理（图中第一条连接）。请教一下如何才能实现bt流量绕过代理走直连，其他流量正常分流的功能呢？

**Comment by UIforFreedom** [comment]
在内核日志中，你确定流量被正确嗅探了？ 我第一感觉就是内核嗅探出错了

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 11 月 24 日星期日 21:41, shakugannokanade ***@***.***(mailto:2024 年 11 月 24 日星期日 21:41, shakugannokanade <<a href=)> 来信：

**Comment by shakugannokanade** [comment]
![image](https://github.com/user-attachments/assets/7078440b-b3e4-43fa-ad57-b29e554e0d92)
看了一会有关这个ip的日志，会出现同时有直连和代理两个连接存在的情况，这是有的流量被识别为bt，有的被识别为正常的意思？

**Comment by UIforFreedom** [comment]
bt 流量不好嗅探，只能说尽力而为

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 11 月 24 日星期日 22:08, shakugannokanade ***@***.***(mailto:2024 年 11 月 24 日星期日 22:08, shakugannokanade <<a href=)> 来信：
