### ISSUE TITLE
docker部署，系统无法走代理

### ISSUE THREAD

**Issue by lm970585581** [UIforFreedom/UIF#48]
使用docker部署后，已经成功导入订阅：
主页测速也已经出来了：
![image](https://github.com/user-attachments/assets/95d705d2-92c4-4938-a707-c34c22da8f05)

![image](https://github.com/user-attachments/assets/2de4bc3d-b658-4101-a779-f6dfe80a1856)
但是在linux服务器中手动设置代理不生效：
![image](https://github.com/user-attachments/assets/e8e0cdf3-6170-440b-877f-02562fb21543)

服务器已经开放9110端口

**Comment by UIforFreedom** [comment]
export 127.0.0.1:9110 试试这个，而不是本机ip

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 11 月 25 日星期一 09:47, H.U.C-王子 ***@***.***(mailto:2024 年 11 月 25 日星期一 09:47, H.U.C-王子 <<a href=)> 来信：

**Comment by lm970585581** [comment]
这个已经试过了，因为不生效所以又试用的服务器的ip
而且入站规则我选用的是公网ip的选项，另外我在本地windows电脑设置网络代理，使用服务器的代理也不生效

![image](https://github.com/user-attachments/assets/bb50dab8-8a6c-4bc3-b382-1ff015b0a3b2)

docker的启动命令也是来自于咱们的文档：docker run --network host --name uif --privileged --restart unless-stopped -d ui4freedom/uif:latest

**Comment by lm970585581** [comment]
另外补充，使用tun模式，服务器也一样不能ping通google
