### ISSUE TITLE
出站标签因特殊国家代码导致不一致，启动sing-box核心失败

### ISSUE THREAD

**Issue by daifiyum** [UIforFreedom/UIF#5]
![image](https://github.com/user-attachments/assets/89d84694-4c28-47cd-826d-9583174d0230)
![image](https://github.com/user-attachments/assets/a8f4f3c9-44c1-4750-936b-3af0d84f8a2f)

**Comment by daifiyum** [comment]
报错：
![image](https://github.com/user-attachments/assets/f51cdf08-b5ba-4fd9-9bba-4a7bcaffc323)

**Comment by UIforFreedom** [comment]
似乎是编码问题，但是不应该啊。你第一张图片中kr是 `core_config.json` 吗？。按理来说，第二张图的 kr 是拼接来的，什么都没改

**Comment by daifiyum** [comment]
> 似乎是编码问题，但是不应该啊。你第一张图片中kr是 `core_config.json` 吗？。按理来说，第二张图的 kr 是拼接来的，什么都没改

都是从`core_config.json` 里面截的图

**Comment by UIforFreedom** [comment]
> > 似乎是编码问题，但是不应该啊。你第一张图片中kr是 `core_config.json` 吗？。按理来说，第二张图的 kr 是拼接来的，什么都没改
> 
> 都是从`core_config.json` 里面截的图

我再看看，目前没有头绪为什么编码会变了。其实我之前就注意到了，但是懒得调试（主要是没人用），所以就忽略了

**Comment by daifiyum** [comment]
> > > 似乎是编码问题，但是不应该啊。你第一张图片中kr是 `core_config.json` 吗？。按理来说，第二张图的 kr 是拼接来的，什么都没改
> > 
> > 
> > 都是从`core_config.json` 里面截的图
> 
> 我再看看，目前没有头绪为什么编码会变了。其实我之前就注意到了，但是懒得调试（主要是没人用），所以就忽略了

你这个项目真是宝藏项目，绝对精品，没人用只是他们看不到优秀的东西吧

**Comment by daifiyum** [comment]
我也写了一个类似的，可以通过webui来订阅，支持托盘菜单开关代理，但也只有这些功能了，其他的配置都是改模板，你这个把配置部分UI化了，很方便

**Comment by UIforFreedom** [comment]
> 我也写了一个类似的，可以通过webui来订阅，支持托盘菜单开关代理，但也只有这些功能了，其他的配置都是改模板，你这个把配置部分UI化了，很方便

你写了支持哪些订阅配置？ 我写了clash-meta、v2rayn 和 v2ray

**Comment by daifiyum** [comment]
> > 我也写了一个类似的，可以通过webui来订阅，支持托盘菜单开关代理，但也只有这些功能了，其他的配置都是改模板，你这个把配置部分UI化了，很方便
> 
> 你写了支持哪些订阅配置？ 我写了clash-meta、v2rayn 和 v2ray

我没写，偷了hiddify的[轮子](https://github.com/hiddify/ray2sing)

**Comment by UIforFreedom** [comment]
我感觉我修好了。如果能提供一下你的订阅来给我测试一下那就更好了。我的telegram: https://t.me/ui4freedom
