### ISSUE TITLE
为什么老是提示后端没有运行？

### ISSUE THREAD

**Issue by cmccryan** [UIforFreedom/UIF#50]
![1111](https://github.com/user-attachments/assets/636403db-00e1-464c-a337-c4f7354a29b7)

**Comment by UIforFreedom** [comment]
订阅转换错误，节点解析的 bug。 私聊我发订阅链接才能修复，或者你直接禁用解析错误的节点

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 11 月 27 日星期三 15:03, cmccryan ***@***.***(mailto:2024 年 11 月 27 日星期三 15:03, cmccryan <<a href=)> 来信：
