### ISSUE TITLE
是否考虑添加多路复用以及padding 选项

### ISSUE THREAD

**Issue by cyclestudy** [UIforFreedom/UIF#54]

**Comment by UIforFreedom** [comment]
tcp 的多路复用建议使用 grpc，这些多路复用都没有本质上的区别，而且无论怎么优化，速度都跑不起来。

最好方法就是直接使用 hysteria2，自带多路复用。

padding 只是用来吓唬小白的， 你很在意的话直接用 hysteria2，因为 quic 本身就有 padding。

如果你有遇到 qos（我从未遇到过，非常质疑是否真的存在），建议你换一个网络提供商。

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 12 月 1 日星期日 13:13, CycleStudies ***@***.***(mailto:2024 年 12 月 1 日星期日 13:13, CycleStudies <<a href=)> 来信：

**Comment by cyclestudy** [comment]
好的，感谢大佬
