### ISSUE TITLE
24.12.04 版在哪下。现在最新下载的路由有问题。

### ISSUE THREAD

**Issue by yvhk750** [UIforFreedom/UIF#55]

**Comment by UIforFreedom** [comment]
有什么问题？

**Comment by yvhk750** [comment]
现在下载那最新的是11.24 使用默认的规则打不开网站。

**Comment by yvhk750** [comment]
还有请问服务端那自签证书要怎么生成才能用啊。 用你那个默认的没有问题。如果用我自己生成的证书和域名确只能跳过证书验证来使用。

**Comment by UIforFreedom** [comment]
> 现在下载那最新的是11.24 使用默认的规则打不开网站。

我自己测试可以打开啊，不知道你发生了什么

**Comment by UIforFreedom** [comment]
> 还有请问服务端那自签证书要怎么生成才能用啊。 用你那个默认的没有问题。如果用我自己生成的证书和域名确只能跳过证书验证来使用。

把你自己 生成好的或机构申请的 证书和密钥粘贴进去就行了。原理都是一样的。

**Comment by yvhk750** [comment]
> > 现在下载那最新的是11.24 使用默认的规则打不开网站。
> 
> 我自己测试可以打开啊，不知道你发生了什么

今天有空看了下。是开了Adguard去广告就会无网。我也不是很懂，看share.json好像是文件287行有问题加"adguard-filter-list"就好了。

**Comment by UIforFreedom** [comment]
> > > 现在下载那最新的是11.24 使用默认的规则打不开网站。
> > 
> > 
> > 我自己测试可以打开啊，不知道你发生了什么
> 
> 今天有空看了下。是开了Adguard去广告就会无网。我也不是很懂，看share.json好像是文件287行有问题加"adguard-filter-list"就好了。

已修复。但是我试了试 [这个数据库](https://github.com/TG-Twilight/AWAvenue-Ads-Rule) 效果还是很差。没有mitm，效果也就那样。
