### ISSUE TITLE
手机arm64报错

### ISSUE THREAD

**Issue by xxsxiao** [UIforFreedom/UIF#59]
FATAL[0000] start service: initialize rule-set[2]: initial rule-set: geosite-private: Get "https://fastly.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-private.srs": exchange6: exchange6: dial udp 223.5.5.5:53: no route to internet | exchange4: dial udp 223.5.5.5:53: no route to internet | exchange4: exchange6: dial udp 223.5.5.5:53: no route to internet | exchange4: dial udp 223.5.5.5:53: no route to internet | initialize rule-set[2]: initial rule-set: geosite-cn: Get "https://fastly.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-geolocation-cn.srs": initialize rule-set[2]: initial rule-set: geosite-private: Get "https://fastly.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-private.srs": exchange6: exchange6: dial udp 223.5.5.5:53: no route to internet | exchange4: dial udp 223.5.5.5:53: no route to internet | exchange4: exchange6: dial udp 223.5.5.5:53: no route to internet | exchange4: dial udp 223.5.5.5:53: no route to internet | initialize rule-set[2]: initial rule-set: geoip-cn: Get "https://fastly.jsdelivr.net/gh/SagerNet/sing-geoip@rule-set/geoip-cn.srs": initialize rule-set[2]: initial rule-set: geosite-private: Get "https://fastly.jsdelivr.net/gh/SagerNet/sing-geosite@rule-set/geosite-private.srs": exchange6: exchange6: dial udp 223.5.5.5:53: no route to internet | exchange4: dial udp 223.5.5.5:53: no route to internet | exchange4: exchange6: dial udp 223.5.5.5:53: no route to internet | exchange4: dial udp 223.5.5.5:53: no route to internet

core err: exit status 1
Get "https://www.github.com": proxyconnect tcp: dial tcp 127.0.0.1:42967: connect: connection refused

Get "https://www.baidu.com": proxyconnect tcp: dial tcp 127.0.0.1:42967: connect: connection refused
Get "https://www.github.com": proxyconnect tcp: dial tcp 127.0.0.1:39101: connect: connection refused

Get "https://www.baidu.com": proxyconnect tcp: dial tcp 127.0.0.1:39101: connect: connection refused
Get "https://www.netflix.com": proxyconnect tcp: dial tcp 127.0.0.1:42967: connect: connection refused
Get "https://www.youtube.com": proxyconnect tcp: dial tcp 127.0.0.1:42967: connect: connection refused

Get "https://www.netflix.com": proxyconnect tcp: dial tcp 127.0.0.1:39101: connect: connection refused

Get "https://www.youtube.com": proxyconnect tcp: dial tcp 127.0.0.1:39101: connect: connection refused
Get "https://www.google.com": proxyconnect tcp: dial tcp 127.0.0.1:42967: connect: connection refused

Get "https://www.google.com": proxyconnect tcp: dial tcp 127.0.0.1:39101: connect: connection refused
Get "https://www.instagram.com": proxyconnect tcp: dial tcp 127.0.0.1:42967: connect: connection refused

Get "https://www.instagram.com": proxyconnect tcp: dial tcp 127.0.0.1:39101: connect: connection refused
![Screenshot_2024-12-10-20-10-16-23_3d419158bad5872c40592a6c9956e692](https://github.com/user-attachments/assets/77d84179-e1df-4a17-a398-3c3f76002652)

**Comment by UIforFreedom** [comment]
看起来像是没有网络，导致无法下载域名数据库

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 12 月 10 日星期二 20:28, 神也眷顾小晓吖. ***@***.***(mailto:2024 年 12 月 10 日星期二 20:28, 神也眷顾小晓吖. <<a href=)> 来信：

**Comment by yvhk750** [comment]
手机换手机内核可以
![image](https://github.com/user-attachments/assets/5b33c30c-f932-452f-95dd-f7b1d826b5ed)
