### ISSUE TITLE
自定义分流报错

### ISSUE THREAD

**Issue by AAEE86** [UIforFreedom/UIF#60]
域名规则使用正则匹配 报错：
```
FATAL[0000] create service: parse route options: parse rule[4]: domain_regex: parse expression 0: error parsing regexp: missing argument to repetition operator: `*`
```

**Comment by UIforFreedom** [comment]
把你写的正则发出来啊，大概率是你写了错误的正则

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 12 月 11 日星期三 08:58, AAEE86 ***@***.***(mailto:2024 年 12 月 11 日星期三 08:58, AAEE86 <<a href=)> 来信：

**Comment by AAEE86** [comment]
*.baidu.com   

系统预设的正则也不行

**Comment by AAEE86** [comment]
@UIforFreedom 
![图片_20241211090650](https://github.com/user-attachments/assets/5f7af08a-b3b9-4a8b-84a1-e6d3ccc6e5e5)

**Comment by UIforFreedom** [comment]
例子给错了，输入的正则应该要符合标准的正则，如果你要匹配 *.baidu.com，正确的表达式：^.*\.baidu\.com

**Comment by AAEE86** [comment]
> 例子给错了，输入的正则应该要符合标准的正则，如果你要匹配 *.baidu.com，正确的表达式：^.*\.baidu\.com

好的
