### ISSUE TITLE
hysteria2 延迟

### ISSUE THREAD

**Issue by lazybabyz** [UIforFreedom/UIF#61]
感谢大佬!体验了一下感觉很便利.
但有一个疑问,在同一服务器上安装了原装hysteria2进行比较,UIF安装的永远会多延迟2百以上有时候会多几百
我可以从哪方面排查呢

原装hysteria2 Linux Shell安装
UIF Linux  Docker安装

感谢回应

**Comment by UIforFreedom** [comment]
你在哪里的测的延迟？

**Comment by lazybabyz** [comment]
> 感谢大佬!

感谢大佬!
