### ISSUE TITLE
分享链接打开为空白

### ISSUE THREAD

**Issue by NLP-Peter** [UIforFreedom/UIF#64]
<img width="1095" alt="微信图片_20241223165318" src="https://github.com/user-attachments/assets/44116c78-dfac-47a6-9c1f-ed2527920765" />
点击分享链接，通过浏览器打开为空白内容，查看源码也是空白，请问是怎么回事？
订阅节点是通过配置文件导入，并非订阅链接。

**Comment by UIforFreedom** [comment]
这是预期行为。你必须要开放公网，并填入密码后才能看到分享内容。

如果不这样做的话就有严重的漏洞，你随便访问一个不相关的网页，对方就可以“偷取”你的订阅内容。
