### ISSUE TITLE
一些优化建议

### ISSUE THREAD

**Issue by aurorax-neo** [UIforFreedom/UIF#65]
1. 能否支持导出入站节点的uri，如：https://v2.hysteria.network/zh/docs/developers/URI-Scheme/
2.能否把以下文件单独放到一个文件夹下，方便管理和 方便 docker 配置映射文件进行持久化（*db 放到程序同目录下的 data 目录，*txt 和*json 放到程序同目录下的 conf 目录）

docker cp uif:/usr/bin/uif/core_config.json /opt/docker/uif/core_config.json
docker cp uif:/usr/bin/uif/uif.json /opt/docker/uif/uif.json
docker cp uif:/usr/bin/uif/geoip.db /opt/docker/uif/geoip.db
docker cp uif:/usr/bin/uif/geosite.db /opt/docker/uif/geosite.db
docker cp uif:/usr/bin/uif/uif_api_address.txt /opt/docker/uif/uif_api_address.txt
docker cp uif:/usr/bin/uif/uif_web_address.txt /opt/docker/uif/uif_web_address.txt
docker cp uif:/usr/bin/uif/uif_key.txt /opt/docker/uif/uif_key.txt

**Comment by UIforFreedom** [comment]
> 能否支持导出入站节点的uri，如：https://v2.hysteria.network/zh/docs/developers/URI-Scheme/

不考虑。因为 UIF 支持自定义证书，这些 uri 一律用 insecure 来代替，本来就是不兼容的配置。UIF 的分享格式更像是 clash 的，而不是 v2rayn 之流。

> 能否把以下文件单独放到一个文件夹下，方便管理和 方便 docker 配置映射文件进行持久化（*db 放到程序同目录下的 data 目录，txt 和json 放到程序同目录下的 conf 目录）

看不懂你想要什么。这个操作优化了什么？

**Comment by aurorax-neo** [comment]
> > 能否支持导出入站节点的uri，如：https://v2.hysteria.network/zh/docs/developers/URI-Scheme/
> 
> 
> 
> 不考虑。因为 UIF 支持自定义证书，这些 uri 一律用 insecure 来代替，本来就是不兼容的配置。UIF 的分享格式更像是 clash 的，而不是 v2rayn 之流。
> 
> 
> 
> > 能否把以下文件单独放到一个文件夹下，方便管理和 方便 docker 配置映射文件进行持久化（*db 放到程序同目录下的 data 目录，txt 和json 放到程序同目录下的 conf 目录）
> 
> 
> 
> 看不懂你想要什么。这个操作优化了什么？

docker 要持久化配置映射的条目有点多

**Comment by aurorax-neo** [comment]
> > 能否支持导出入站节点的uri，如：https://v2.hysteria.network/zh/docs/developers/URI-Scheme/
> 
> 
> 
> 不考虑。因为 UIF 支持自定义证书，这些 uri 一律用 insecure 来代替，本来就是不兼容的配置。UIF 的分享格式更像是 clash 的，而不是 v2rayn 之流。
> 
> 
> 
> > 能否把以下文件单独放到一个文件夹下，方便管理和 方便 docker 配置映射文件进行持久化（*db 放到程序同目录下的 data 目录，txt 和json 放到程序同目录下的 conf 目录）
> 
> 
> 
> 看不懂你想要什么。这个操作优化了什么？

好的 谢谢回复 uri 相关问题，我只是考虑用导出的 uri 进行订阅转化成 clash 配置

**Comment by UIforFreedom** [comment]
> docker 要持久化配置映射的条目有点多

为什么要持久化？
