### ISSUE TITLE
alpine 解压后，给权限,运行uif 停在这画面

### ISSUE THREAD

**Issue by maxkingmax** [UIforFreedom/UIF#8]
![image](https://github.com/user-attachments/assets/e8b03046-3423-4d5f-ba25-2f1961187c34)

**Comment by UIforFreedom** [comment]
看起来已经是正常运行了。但是此时你无法访问Web UI，出于安全的原因，UIF默认是监听 `127.0.0.1:9413` 的，可以参考 [修改api监听端口](http://ui4freedom.org/UIF_help/docs/setting#%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4-web-%E5%92%8C-api-%E5%9C%B0%E5%9D%80%E5%92%8C%E7%AB%AF%E5%8F%A3)。

alpine 属于比较小众的，连 systemd 都没有，用不了一键脚本。或者你私聊 [我 telegram](https://t.me/ui4freedom) 来做适配。

**Comment by UIforFreedom** [comment]
已修好。
